name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --registry=https://registry.npmmirror.com
      # - name: Run tests
      #   run: pnpm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image locally
        run: docker build -t gosuquan/node-test:latest .
      - name: Save Docker image as tar
        run: docker save -o node-test.tar gosuquan/node-test:latest
      - name: Remove old tar on server (if any)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf ~/app/node-test.tar
      - name: Upload Docker image tar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "node-test.tar"
          target: "~/app/node-test.tar"
      # 可选：推送到 Docker Hub 作为备份
      - name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: gosuquan/node-test:latest
          cache-from: type=registry,ref=gosuquan/node-test:buildcache
          cache-to: type=inline

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |-
            # 进入应用目录
            mkdir -p ~/app
            cd ~/app
            # 检查 node-test.tar 必须为普通文件
            if [ ! -f node-test.tar ]; then
              echo '错误: node-test.tar 不是普通文件！实际类型如下：'
              ls -l node-test.tar
              file node-test.tar
              exit 1
            fi
            echo 'node-test.tar 文件类型如下：'
            ls -l node-test.tar
            file node-test.tar
            # 导入镜像
            docker load -i node-test.tar
            # 清理旧容器
            docker stop node-test || true
            docker rm node-test || true
            # 运行新容器
            docker run -d --name node-test --restart unless-stopped -p 3000:3000 -e NODE_ENV=production -e DB_HOST=${{ secrets.DB_HOST }} gosuquan/node-test:latest
            # 验证
            docker ps
            curl -I http://localhost:3000 || true