name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    
    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile --registry=https://registry.npmmirror.com
      
    # - name: Run tests
    #   run: pnpm test
      
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gosuquan/node-test:latest
        cache-from: type=registry,ref=gosuquan/node-test:buildcache
        cache-to: type=inline
    
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |2
          # 检查 Docker 是否安装
          if ! command -v docker &> /dev/null; then
            echo "Docker 未安装，正在安装..."
            # 安装 Docker
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            # 将当前用户添加到 docker 组
            sudo usermod -aG docker $USER
            # 重新加载 shell 以使用户组变更生效
            newgrp docker
          fi
          
          # 配置 Docker 使用国内镜像源
          echo "配置 Docker 镜像加速..."
          sudo mkdir -p /etc/docker
          echo '{"registry-mirrors":["https://registry.docker-cn.com","https://hub-mirror.c.163.com","https://mirror.baidubce.com"]}' | sudo tee /etc/docker/daemon.json
          
          # 重启 Docker 服务
          sudo systemctl daemon-reload
          sudo systemctl restart docker
          
          # 部署应用，使用更简单的方式处理网络问题
          echo "拉取 Docker 镜像..."
          # 设置更长的超时时间并使用国内镜像
          docker pull registry.cn-hangzhou.aliyuncs.com/gosuquan/node-test:latest || docker pull gosuquan/node-test:latest || true
          
          # 如果拉取失败，使用本地镜像或构建新镜像
          if ! docker images | grep -q 'gosuquan/node-test'; then
            echo "镜像拉取失败，使用本地构建..."
            mkdir -p ~/app && cd ~/app
            # 如果已有代码，尝试更新，否则克隆
            if [ -d ".git" ]; then
              git pull
            else
              git clone https://github.com/GosuQuan/From-0-to-1-Enterprise-level-High-Availability-Node.js-Server.git .
            fi
            docker build -t gosuquan/node-test:latest .
          fi
          
          echo "停止并移除旧容器..."
          docker stop node-test || true
          docker rm node-test || true
          
          echo "启动新容器..."
          docker run -d \
            --name node-test \
            --restart unless-stopped \
            -p 3000:3000 \
            -e NODE_ENV=production \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            gosuquan/node-test:latest
          
          echo "部署完成！"
          docker ps | grep node-test